### ISSUE TITLE
PhET-iO API error when using 'screens' query parameter 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#190]
See https://github.com/phetsims/tandem/issues/194.   No idea if I need to address this for ph-scale RC.

**Comment by pixelzoom** [comment]
This apparently does need to be addressed for RC.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/tandem/issues/194 has been addressed and verified in master. But I've hit a merge conflict trying to cherry-pick the changes, see https://github.com/phetsims/tandem/issues/194#issuecomment-666807225.  I'll need assistance from @zepumph.

**Comment by pixelzoom** [comment]
@zepumph provide details on how to resolve merge conflicts in https://github.com/phetsims/tandem/issues/194#issuecomment-667192017, so I'll try again.

**Comment by pixelzoom** [comment]
I resolved the merge conflict in phetioApiValidation.js by changing this:

```js
    this.enabled = assert &&
                   Tandem.VALIDATION &&
                   phet.chipper.queryParameters.screens === null &&
                   phet.chipper.queryParameters.homeScreen;
```

... to this:

```js
    this.enabled = assert &&
                   Tandem. PHET_IO_ENABLED &&
                   phet.chipper.queryParameters.screens === null &&
                   phet.chipper.queryParameters.homeScreen;
```

Seems to work OK in ph-scale 1.4 and ph-scale-basics-1.4, but makes me nervous to be doing partial cherry-picks.

Ready for testing in next RC.

**Comment by pixelzoom** [comment]
To verify in ph-scale 1.4.0-rc.2:

1. Run the sim in Studio with `?screens=1`
2. Verify that there are no errors in the console.

It is expected that all 3 screens will still be shown in the Studio tree.

**Comment by brooklynlash** [comment]
No API error and no console issues, all screens are still showed in the Studio tree but only the name property.

**Comment by pixelzoom** [comment]
> ...  all screens are still showed in the Studio tree but  only the name property.

@brooklynlash You're probably only seeing `nameProperty` for screens in Studio because you have the "Featured" radio button selected for "PhET-iO Elements".  You'll need to select the "All" radio button.   Please verify that that is the case.

**Comment by brooklynlash** [comment]
Yes, my mistake. I need to remember to do that next time

**Comment by pixelzoom** [comment]
Great, thanks. Closing.
